# Generated by Django 4.2.6 on 2023-10-30 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(blank=True, max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('criado', models.DateTimeField(default=django.utils.timezone.now)),
                ('desc', models.TextField(blank=True)),
                ('mostrar', models.BooleanField(default=False)),
                ('imagem', models.ImageField(blank=True, upload_to='imagens/%Y/%m/')),
            ],
        ),
    ]
