# Generated by Django 5.0 on 2023-12-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contato", "0003_alter_categoria_options_contato_criador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contato",
            name="mostrar",
            field=models.BooleanField(default=True),
        ),
    ]
